/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author Usuario
 */
public class EstRealizados extends javax.swing.JFrame {

    /**
     * Creates new form EstRealizados
     */
    public EstRealizados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        rdPrimariaSi = new javax.swing.JRadioButton();
        rdPrimariaNo = new javax.swing.JRadioButton();
        rdSecundariaSi = new javax.swing.JRadioButton();
        rdSecundariaNo = new javax.swing.JRadioButton();
        rdUniversidadSi = new javax.swing.JRadioButton();
        rdUniversidadNo = new javax.swing.JRadioButton();
        rdTeologicoSi = new javax.swing.JRadioButton();
        rdTeologicoNo = new javax.swing.JRadioButton();
        txtUltimoEstud = new javax.swing.JTextField();
        rdSeminarioSi = new javax.swing.JRadioButton();
        rdSeminarioNo = new javax.swing.JRadioButton();
        txtDirecSeminario = new javax.swing.JTextField();
        txtxIdiomas = new javax.swing.JTextField();
        txtInstSemimario = new javax.swing.JTextField();
        FechaEstu = new com.toedter.calendar.JDateChooser();
        jlbFondoEstRea = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel2.setText("Estudios realizados");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(200, 20, 460, 40);

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel3.setText("¿Aprobó toda la primaria?");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 150, 210, 18);

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel4.setText("¿Aprobó toda la secundaria?");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 220, 230, 18);

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel5.setText("¿Aprobó estudios técnicos o universitarios?");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 290, 330, 18);

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel6.setText("Institución donde aprobó su último estudio:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 360, 340, 18);

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel7.setText("¿Ha realizado estudios teológicos?");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 440, 270, 18);

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel8.setText("Fecha en que realizó sus estudios teológicos:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(440, 140, 350, 30);

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel9.setText("¿Ha realizado seminarios bíblicos?");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(440, 220, 260, 18);

        jLabel10.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel10.setText("Institución donde ha realizado seminarios bíblicos:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(440, 290, 400, 18);

        jLabel11.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel11.setText("Dirección de la institución:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(440, 360, 203, 10);

        jLabel12.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel12.setText("¿Qué idiomas conoce?");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(440, 440, 190, 18);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btGuardar.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setIconTextGap(-3);
        jButton1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jButton1);
        jButton1.setBounds(210, 560, 170, 70);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BtCancelar.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setIconTextGap(-3);
        jButton2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jButton2);
        jButton2.setBounds(430, 560, 160, 70);

        rdPrimariaSi.setBackground(new java.awt.Color(255, 255, 255));
        rdPrimariaSi.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        rdPrimariaSi.setText("Sí");
        rdPrimariaSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdPrimariaSiActionPerformed(evt);
            }
        });
        getContentPane().add(rdPrimariaSi);
        rdPrimariaSi.setBounds(70, 180, 40, 25);

        rdPrimariaNo.setBackground(new java.awt.Color(255, 255, 255));
        rdPrimariaNo.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        rdPrimariaNo.setText("No");
        getContentPane().add(rdPrimariaNo);
        rdPrimariaNo.setBounds(120, 180, 50, 25);

        rdSecundariaSi.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        rdSecundariaSi.setText("Sí");
        getContentPane().add(rdSecundariaSi);
        rdSecundariaSi.setBounds(70, 250, 40, 25);

        rdSecundariaNo.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        rdSecundariaNo.setText("No");
        getContentPane().add(rdSecundariaNo);
        rdSecundariaNo.setBounds(120, 250, 50, 25);

        rdUniversidadSi.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        rdUniversidadSi.setText("Sí");
        getContentPane().add(rdUniversidadSi);
        rdUniversidadSi.setBounds(70, 320, 40, 25);

        rdUniversidadNo.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        rdUniversidadNo.setText("No");
        getContentPane().add(rdUniversidadNo);
        rdUniversidadNo.setBounds(120, 320, 50, 25);

        rdTeologicoSi.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        rdTeologicoSi.setText("Sí");
        rdTeologicoSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdTeologicoSiActionPerformed(evt);
            }
        });
        getContentPane().add(rdTeologicoSi);
        rdTeologicoSi.setBounds(70, 470, 40, 25);

        rdTeologicoNo.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        rdTeologicoNo.setText("No");
        getContentPane().add(rdTeologicoNo);
        rdTeologicoNo.setBounds(120, 470, 50, 25);

        txtUltimoEstud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUltimoEstudActionPerformed(evt);
            }
        });
        getContentPane().add(txtUltimoEstud);
        txtUltimoEstud.setBounds(40, 390, 300, 30);

        rdSeminarioSi.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        rdSeminarioSi.setText("Sí");
        rdSeminarioSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdSeminarioSiActionPerformed(evt);
            }
        });
        getContentPane().add(rdSeminarioSi);
        rdSeminarioSi.setBounds(470, 250, 40, 25);

        rdSeminarioNo.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        rdSeminarioNo.setText("No");
        getContentPane().add(rdSeminarioNo);
        rdSeminarioNo.setBounds(520, 250, 50, 25);

        txtDirecSeminario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDirecSeminarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtDirecSeminario);
        txtDirecSeminario.setBounds(440, 390, 350, 30);

        txtxIdiomas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtxIdiomasActionPerformed(evt);
            }
        });
        getContentPane().add(txtxIdiomas);
        txtxIdiomas.setBounds(440, 470, 350, 30);

        txtInstSemimario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInstSemimarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtInstSemimario);
        txtInstSemimario.setBounds(440, 320, 350, 30);

        FechaEstu.setDateFormatString("yyyy/MM/dd");
        FechaEstu.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        getContentPane().add(FechaEstu);
        FechaEstu.setBounds(440, 180, 240, 30);

        jlbFondoEstRea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo14.png"))); // NOI18N
        getContentPane().add(jlbFondoEstRea);
        jlbFondoEstRea.setBounds(0, 0, 880, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdPrimariaSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdPrimariaSiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdPrimariaSiActionPerformed

    private void rdTeologicoSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdTeologicoSiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdTeologicoSiActionPerformed

    private void txtUltimoEstudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUltimoEstudActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUltimoEstudActionPerformed

    private void rdSeminarioSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdSeminarioSiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdSeminarioSiActionPerformed

    private void txtDirecSeminarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDirecSeminarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDirecSeminarioActionPerformed

    private void txtxIdiomasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtxIdiomasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtxIdiomasActionPerformed

    private void txtInstSemimarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInstSemimarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInstSemimarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EstRealizados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EstRealizados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EstRealizados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EstRealizados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EstRealizados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser FechaEstu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jlbFondoEstRea;
    private javax.swing.JRadioButton rdPrimariaNo;
    private javax.swing.JRadioButton rdPrimariaSi;
    private javax.swing.JRadioButton rdSecundariaNo;
    private javax.swing.JRadioButton rdSecundariaSi;
    private javax.swing.JRadioButton rdSeminarioNo;
    private javax.swing.JRadioButton rdSeminarioSi;
    private javax.swing.JRadioButton rdTeologicoNo;
    private javax.swing.JRadioButton rdTeologicoSi;
    private javax.swing.JRadioButton rdUniversidadNo;
    private javax.swing.JRadioButton rdUniversidadSi;
    private javax.swing.JTextField txtDirecSeminario;
    private javax.swing.JTextField txtInstSemimario;
    private javax.swing.JTextField txtUltimoEstud;
    private javax.swing.JTextField txtxIdiomas;
    // End of variables declaration//GEN-END:variables
}
