/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author Usuario
 */
public class InfPersonal extends javax.swing.JFrame {

    /**
     * Creates new form InfPersonal
     */
    public InfPersonal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jTextField19 = new javax.swing.JTextField();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jTextField20 = new javax.swing.JTextField();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jTextField21 = new javax.swing.JTextField();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        jLabel1.setText("Información personal");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(190, 10, 700, 68);

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel3.setText("Nombres:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 130, 65, 17);

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel4.setText("Apellidos:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 180, 70, 17);

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel5.setText("Fecha de nacimiento:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(710, 180, 150, 17);

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel6.setText("Lugar de nacimiento:");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 230, 150, 17);

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel7.setText("Cédula o pasaporte:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 280, 150, 17);

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel8.setText("Sexo:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(710, 130, 50, 17);

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel9.setText("Correo electrónico:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 330, 134, 17);

        jLabel10.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel10.setText("Nro. de celular:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(30, 430, 110, 17);

        jLabel11.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel11.setText("Cantidad de hijos:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(710, 230, 140, 17);

        jLabel12.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel12.setText("Dependen económicamente de usted:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(710, 280, 260, 17);

        jLabel13.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel13.setText("Nombres de los hijos de mayor a menor:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(710, 330, 290, 17);

        jLabel14.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel14.setText("Seguro de salud al que pertenece:");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(330, 130, 240, 17);

        jLabel15.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel15.setText("Nivel de educación:");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(30, 480, 150, 17);

        jLabel16.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel16.setText("¿Es pensionado?");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(710, 380, 130, 17);

        jLabel17.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel17.setText("Nombre de la empresa donde se pensionó:");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(710, 430, 310, 17);

        jLabel18.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel18.setText("¿Tiene casa propia?");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(710, 480, 150, 17);

        jLabel19.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel19.setText("Estrato donde vive:");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(30, 530, 140, 17);

        jLabel20.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel20.setText("Dirección de residencia:");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(30, 580, 180, 17);

        jLabel21.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel21.setText("Teléfono fijo:");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(30, 380, 100, 14);

        jLabel22.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel22.setText("Nombre de la anterior organización perteneciente:");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(330, 180, 360, 20);

        jLabel23.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel23.setText("Teléfono fijo de la organización:");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(330, 230, 230, 17);

        jLabel24.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel24.setText("Recomendación personal:");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(330, 280, 190, 17);

        jLabel25.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel25.setText("Teléfono de la persona que lo recomienda:");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(330, 330, 310, 17);

        jLabel26.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel26.setText("Dirección de la Iglesia que pastorea:");
        getContentPane().add(jLabel26);
        jLabel26.setBounds(330, 380, 260, 17);

        jLabel27.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel27.setText("Nombre de la persona responsable de la Iglesia:");
        getContentPane().add(jLabel27);
        jLabel27.setBounds(330, 430, 340, 17);

        jLabel28.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel28.setText("Teléfono de la Iglesia:");
        getContentPane().add(jLabel28);
        jLabel28.setBounds(330, 480, 170, 17);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(330, 500, 280, 20);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(30, 200, 230, 20);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(30, 250, 230, 20);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(30, 300, 230, 20);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(30, 350, 230, 20);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(30, 400, 230, 20);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(30, 450, 230, 20);
        getContentPane().add(jTextField8);
        jTextField8.setBounds(30, 500, 230, 20);
        getContentPane().add(jTextField9);
        jTextField9.setBounds(30, 600, 230, 20);
        getContentPane().add(jTextField10);
        jTextField10.setBounds(30, 550, 230, 20);

        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField11);
        jTextField11.setBounds(30, 150, 230, 20);

        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField12);
        jTextField12.setBounds(330, 150, 280, 20);

        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField13);
        jTextField13.setBounds(330, 200, 280, 20);

        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField14);
        jTextField14.setBounds(710, 450, 270, 20);

        jTextField15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField15ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField15);
        jTextField15.setBounds(330, 300, 280, 20);

        jTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField16ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField16);
        jTextField16.setBounds(330, 350, 280, 20);

        jTextField17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField17ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField17);
        jTextField17.setBounds(330, 400, 280, 20);

        jTextField18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField18ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField18);
        jTextField18.setBounds(330, 450, 280, 20);

        jRadioButton1.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jRadioButton1.setText("Masculino");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(830, 150, 100, 25);

        jRadioButton2.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jRadioButton2.setText("No");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(760, 500, 50, 25);

        jTextField19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField19ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField19);
        jTextField19.setBounds(330, 250, 280, 20);

        jRadioButton3.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jRadioButton3.setText("Fememino");
        getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(710, 150, 100, 25);

        jRadioButton4.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jRadioButton4.setText("Sí");
        getContentPane().add(jRadioButton4);
        jRadioButton4.setBounds(710, 500, 40, 25);

        jTextField20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField20ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField20);
        jTextField20.setBounds(710, 250, 270, 20);

        jRadioButton5.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jRadioButton5.setText("Sí");
        getContentPane().add(jRadioButton5);
        jRadioButton5.setBounds(710, 300, 40, 25);

        jRadioButton6.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jRadioButton6.setText("No");
        getContentPane().add(jRadioButton6);
        jRadioButton6.setBounds(760, 300, 50, 25);

        jTextField21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField21ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField21);
        jTextField21.setBounds(710, 350, 270, 20);

        jRadioButton7.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jRadioButton7.setText("Sí");
        getContentPane().add(jRadioButton7);
        jRadioButton7.setBounds(710, 400, 40, 25);

        jRadioButton8.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jRadioButton8.setText("No");
        getContentPane().add(jRadioButton8);
        jRadioButton8.setBounds(760, 400, 50, 25);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btGuardar.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setIconTextGap(-3);
        jButton1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jButton1);
        jButton1.setBounds(420, 640, 150, 70);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BtCancelar.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jButton2);
        jButton2.setBounds(580, 640, 150, 70);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo12.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1030, 710);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void jTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField15ActionPerformed

    private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16ActionPerformed

    private void jTextField17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField17ActionPerformed

    private void jTextField18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField18ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jTextField19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField19ActionPerformed

    private void jTextField20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField20ActionPerformed

    private void jTextField21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField21ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InfPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InfPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InfPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InfPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InfPersonal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
