/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author Usuario
 */
public class InfPersonal extends javax.swing.JFrame {

    /**
     * Creates new form InfPersonal
     */
    public InfPersonal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtTelefIgle = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtLugarNac = new javax.swing.JTextField();
        txtxCedula = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();
        txtNivelEduc = new javax.swing.JTextField();
        txtDirecResidencia = new javax.swing.JTextField();
        txtEstrato = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        txtSeguro = new javax.swing.JTextField();
        txtAntOrganiz = new javax.swing.JTextField();
        txtNomEmprPensi = new javax.swing.JTextField();
        txtRecomendacionP = new javax.swing.JTextField();
        txtTelefRecom = new javax.swing.JTextField();
        txtDirecIglesia = new javax.swing.JTextField();
        txtNomResponIgle = new javax.swing.JTextField();
        rdMasculino = new javax.swing.JRadioButton();
        rdCasaNo = new javax.swing.JRadioButton();
        txtTelefOrganiz = new javax.swing.JTextField();
        rdFemenino = new javax.swing.JRadioButton();
        rdCasaSi = new javax.swing.JRadioButton();
        txtCantHijos = new javax.swing.JTextField();
        rdDepenSi = new javax.swing.JRadioButton();
        rdDepenNo = new javax.swing.JRadioButton();
        txtNomHijos = new javax.swing.JTextField();
        rsPensionadoSi = new javax.swing.JRadioButton();
        rdPensionadoNo = new javax.swing.JRadioButton();
        btnGuardar = new javax.swing.JButton();
        BtnCancelar = new javax.swing.JButton();
        jlbFondoInfP = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        jLabel1.setText("Información personal");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(190, 10, 700, 68);

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel3.setText("Nombres:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 130, 65, 17);

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel4.setText("Apellidos:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 180, 70, 17);

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel5.setText("Fecha de nacimiento:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(710, 180, 150, 17);

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel6.setText("Lugar de nacimiento:");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 230, 150, 17);

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel7.setText("Cédula o pasaporte:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 280, 150, 17);

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel8.setText("Sexo:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(710, 130, 50, 17);

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel9.setText("Correo electrónico:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 330, 134, 17);

        jLabel10.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel10.setText("Nro. de celular:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(30, 430, 110, 17);

        jLabel11.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel11.setText("Cantidad de hijos:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(710, 230, 140, 17);

        jLabel12.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel12.setText("Dependen económicamente de usted:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(710, 280, 260, 17);

        jLabel13.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel13.setText("Nombres de los hijos de mayor a menor:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(710, 330, 290, 17);

        jLabel14.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel14.setText("Seguro de salud al que pertenece:");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(330, 130, 240, 17);

        jLabel15.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel15.setText("Nivel de educación:");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(30, 480, 150, 17);

        jLabel16.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel16.setText("¿Es pensionado?");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(710, 380, 130, 17);

        jLabel17.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel17.setText("Nombre de la empresa donde se pensionó:");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(710, 430, 310, 17);

        jLabel18.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel18.setText("¿Tiene casa propia?");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(710, 480, 150, 17);

        jLabel19.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel19.setText("Estrato donde vive:");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(30, 530, 140, 17);

        jLabel20.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel20.setText("Dirección de residencia:");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(30, 580, 180, 17);

        jLabel21.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel21.setText("Teléfono fijo:");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(30, 380, 100, 14);

        jLabel22.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel22.setText("Nombre de la anterior organización perteneciente:");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(330, 180, 360, 20);

        jLabel23.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel23.setText("Teléfono fijo de la organización:");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(330, 230, 230, 17);

        jLabel24.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel24.setText("Recomendación personal:");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(330, 280, 190, 17);

        jLabel25.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel25.setText("Teléfono de la persona que lo recomienda:");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(330, 330, 310, 17);

        jLabel26.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel26.setText("Dirección de la Iglesia que pastorea:");
        getContentPane().add(jLabel26);
        jLabel26.setBounds(330, 380, 260, 17);

        jLabel27.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel27.setText("Nombre de la persona responsable de la Iglesia:");
        getContentPane().add(jLabel27);
        jLabel27.setBounds(330, 430, 340, 17);

        jLabel28.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel28.setText("Teléfono de la Iglesia:");
        getContentPane().add(jLabel28);
        jLabel28.setBounds(330, 480, 170, 17);

        txtTelefIgle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefIgleActionPerformed(evt);
            }
        });
        getContentPane().add(txtTelefIgle);
        txtTelefIgle.setBounds(330, 500, 280, 20);
        getContentPane().add(txtApellidos);
        txtApellidos.setBounds(30, 200, 230, 20);
        getContentPane().add(txtLugarNac);
        txtLugarNac.setBounds(30, 250, 230, 20);
        getContentPane().add(txtxCedula);
        txtxCedula.setBounds(30, 300, 230, 20);
        getContentPane().add(txtCorreo);
        txtCorreo.setBounds(30, 350, 230, 20);
        getContentPane().add(txtTelefono);
        txtTelefono.setBounds(30, 400, 230, 20);
        getContentPane().add(txtCelular);
        txtCelular.setBounds(30, 450, 230, 20);
        getContentPane().add(txtNivelEduc);
        txtNivelEduc.setBounds(30, 500, 230, 20);
        getContentPane().add(txtDirecResidencia);
        txtDirecResidencia.setBounds(30, 600, 230, 20);
        getContentPane().add(txtEstrato);
        txtEstrato.setBounds(30, 550, 230, 20);

        txtNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombresActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombres);
        txtNombres.setBounds(30, 150, 230, 20);

        txtSeguro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSeguroActionPerformed(evt);
            }
        });
        getContentPane().add(txtSeguro);
        txtSeguro.setBounds(330, 150, 280, 20);

        txtAntOrganiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAntOrganizActionPerformed(evt);
            }
        });
        getContentPane().add(txtAntOrganiz);
        txtAntOrganiz.setBounds(330, 200, 280, 20);

        txtNomEmprPensi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomEmprPensiActionPerformed(evt);
            }
        });
        getContentPane().add(txtNomEmprPensi);
        txtNomEmprPensi.setBounds(710, 450, 270, 20);

        txtRecomendacionP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRecomendacionPActionPerformed(evt);
            }
        });
        getContentPane().add(txtRecomendacionP);
        txtRecomendacionP.setBounds(330, 300, 280, 20);

        txtTelefRecom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefRecomActionPerformed(evt);
            }
        });
        getContentPane().add(txtTelefRecom);
        txtTelefRecom.setBounds(330, 350, 280, 20);

        txtDirecIglesia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDirecIglesiaActionPerformed(evt);
            }
        });
        getContentPane().add(txtDirecIglesia);
        txtDirecIglesia.setBounds(330, 400, 280, 20);

        txtNomResponIgle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomResponIgleActionPerformed(evt);
            }
        });
        getContentPane().add(txtNomResponIgle);
        txtNomResponIgle.setBounds(330, 450, 280, 20);

        rdMasculino.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        rdMasculino.setText("Masculino");
        rdMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdMasculinoActionPerformed(evt);
            }
        });
        getContentPane().add(rdMasculino);
        rdMasculino.setBounds(830, 150, 100, 25);

        rdCasaNo.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        rdCasaNo.setText("No");
        getContentPane().add(rdCasaNo);
        rdCasaNo.setBounds(760, 500, 50, 25);

        txtTelefOrganiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefOrganizActionPerformed(evt);
            }
        });
        getContentPane().add(txtTelefOrganiz);
        txtTelefOrganiz.setBounds(330, 250, 280, 20);

        rdFemenino.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        rdFemenino.setText("Fememino");
        getContentPane().add(rdFemenino);
        rdFemenino.setBounds(710, 150, 100, 25);

        rdCasaSi.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        rdCasaSi.setText("Sí");
        getContentPane().add(rdCasaSi);
        rdCasaSi.setBounds(710, 500, 40, 25);

        txtCantHijos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantHijosActionPerformed(evt);
            }
        });
        getContentPane().add(txtCantHijos);
        txtCantHijos.setBounds(710, 250, 100, 20);

        rdDepenSi.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        rdDepenSi.setText("Sí");
        getContentPane().add(rdDepenSi);
        rdDepenSi.setBounds(710, 300, 40, 25);

        rdDepenNo.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        rdDepenNo.setText("No");
        getContentPane().add(rdDepenNo);
        rdDepenNo.setBounds(760, 300, 50, 25);

        txtNomHijos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomHijosActionPerformed(evt);
            }
        });
        getContentPane().add(txtNomHijos);
        txtNomHijos.setBounds(710, 350, 270, 20);

        rsPensionadoSi.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        rsPensionadoSi.setText("Sí");
        getContentPane().add(rsPensionadoSi);
        rsPensionadoSi.setBounds(710, 400, 40, 25);

        rdPensionadoNo.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        rdPensionadoNo.setText("No");
        getContentPane().add(rdPensionadoNo);
        rdPensionadoNo.setBounds(760, 400, 50, 25);

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btGuardar.png"))); // NOI18N
        btnGuardar.setBorder(null);
        btnGuardar.setBorderPainted(false);
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardar.setIconTextGap(-3);
        btnGuardar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(btnGuardar);
        btnGuardar.setBounds(420, 640, 150, 70);

        BtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BtCancelar.png"))); // NOI18N
        BtnCancelar.setBorder(null);
        BtnCancelar.setBorderPainted(false);
        BtnCancelar.setContentAreaFilled(false);
        BtnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnCancelar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BtnCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(BtnCancelar);
        BtnCancelar.setBounds(580, 640, 150, 70);

        jlbFondoInfP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo12.png"))); // NOI18N
        getContentPane().add(jlbFondoInfP);
        jlbFondoInfP.setBounds(0, 0, 1030, 710);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTelefIgleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefIgleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefIgleActionPerformed

    private void txtNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombresActionPerformed

    private void txtSeguroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSeguroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSeguroActionPerformed

    private void txtAntOrganizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAntOrganizActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAntOrganizActionPerformed

    private void txtNomEmprPensiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomEmprPensiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomEmprPensiActionPerformed

    private void txtRecomendacionPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRecomendacionPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRecomendacionPActionPerformed

    private void txtTelefRecomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefRecomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefRecomActionPerformed

    private void txtDirecIglesiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDirecIglesiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDirecIglesiaActionPerformed

    private void txtNomResponIgleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomResponIgleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomResponIgleActionPerformed

    private void rdMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdMasculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdMasculinoActionPerformed

    private void txtTelefOrganizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefOrganizActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefOrganizActionPerformed

    private void txtCantHijosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantHijosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantHijosActionPerformed

    private void txtNomHijosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomHijosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomHijosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InfPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InfPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InfPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InfPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InfPersonal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jlbFondoInfP;
    private javax.swing.JRadioButton rdCasaNo;
    private javax.swing.JRadioButton rdCasaSi;
    private javax.swing.JRadioButton rdDepenNo;
    private javax.swing.JRadioButton rdDepenSi;
    private javax.swing.JRadioButton rdFemenino;
    private javax.swing.JRadioButton rdMasculino;
    private javax.swing.JRadioButton rdPensionadoNo;
    private javax.swing.JRadioButton rsPensionadoSi;
    private javax.swing.JTextField txtAntOrganiz;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCantHijos;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDirecIglesia;
    private javax.swing.JTextField txtDirecResidencia;
    private javax.swing.JTextField txtEstrato;
    private javax.swing.JTextField txtLugarNac;
    private javax.swing.JTextField txtNivelEduc;
    private javax.swing.JTextField txtNomEmprPensi;
    private javax.swing.JTextField txtNomHijos;
    private javax.swing.JTextField txtNomResponIgle;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtRecomendacionP;
    private javax.swing.JTextField txtSeguro;
    private javax.swing.JTextField txtTelefIgle;
    private javax.swing.JTextField txtTelefOrganiz;
    private javax.swing.JTextField txtTelefRecom;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtxCedula;
    // End of variables declaration//GEN-END:variables
}
