/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyListener;
import java.awt.event.MouseListener;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Usuario
 */
public class Menus extends  javax.swing.JFrame implements IVista {

    /**
     * Creates new form Menus
     */
    public Menus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnInfPersonal = new javax.swing.JButton();
        btnDatLab = new javax.swing.JButton();
        btnDatMinis = new javax.swing.JButton();
        btnEstudRea = new javax.swing.JButton();
        btnDocAnex = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lbpastorname = new javax.swing.JLabel();
        btnMatrimonio = new javax.swing.JButton();
        btnEconomica = new javax.swing.JButton();
        btnIglesia = new javax.swing.JButton();
        btnOrganizacion = new javax.swing.JButton();
        jlbFondoMenu = new javax.swing.JLabel();

        setTitle("Menú");
        setLocation(new java.awt.Point(0, 0));
        setPreferredSize(new java.awt.Dimension(657, 523));
        setSize(new java.awt.Dimension(657, 523));
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnInfPersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnpersonal.png"))); // NOI18N
        btnInfPersonal.setToolTipText("");
        btnInfPersonal.setActionCommand("infopersonal");
        btnInfPersonal.setBorder(null);
        btnInfPersonal.setBorderPainted(false);
        btnInfPersonal.setContentAreaFilled(false);
        btnInfPersonal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnInfPersonal.setIconTextGap(-3);
        btnInfPersonal.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnInfPersonal.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(btnInfPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 180, 50));

        btnDatLab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnLaborales.png"))); // NOI18N
        btnDatLab.setActionCommand("infolaboral");
        btnDatLab.setBorder(null);
        btnDatLab.setBorderPainted(false);
        btnDatLab.setContentAreaFilled(false);
        btnDatLab.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDatLab.setIconTextGap(-3);
        btnDatLab.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnDatLab.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(btnDatLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 180, 50));

        btnDatMinis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnministerial.png"))); // NOI18N
        btnDatMinis.setActionCommand("infoministerial");
        btnDatMinis.setBorder(null);
        btnDatMinis.setBorderPainted(false);
        btnDatMinis.setContentAreaFilled(false);
        btnDatMinis.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDatMinis.setIconTextGap(-3);
        btnDatMinis.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnDatMinis.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(btnDatMinis, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, -1, 50));

        btnEstudRea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnEstudios.png"))); // NOI18N
        btnEstudRea.setActionCommand("infoestudios");
        btnEstudRea.setBorder(null);
        btnEstudRea.setBorderPainted(false);
        btnEstudRea.setContentAreaFilled(false);
        btnEstudRea.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEstudRea.setIconTextGap(-3);
        btnEstudRea.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnEstudRea.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEstudRea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstudReaActionPerformed(evt);
            }
        });
        getContentPane().add(btnEstudRea, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, -1, 50));

        btnDocAnex.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnAnexos.png"))); // NOI18N
        btnDocAnex.setActionCommand("documentos");
        btnDocAnex.setBorder(null);
        btnDocAnex.setBorderPainted(false);
        btnDocAnex.setContentAreaFilled(false);
        btnDocAnex.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDocAnex.setIconTextGap(-3);
        btnDocAnex.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnDocAnex.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(btnDocAnex, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 510, -1, 50));

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BtGuard.png"))); // NOI18N
        btnGuardar.setBorder(null);
        btnGuardar.setBorderPainted(false);
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 530, 130, 50));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BtSalir.png"))); // NOI18N
        btnSalir.setActionCommand("salir");
        btnSalir.setBorder(null);
        btnSalir.setBorderPainted(false);
        btnSalir.setContentAreaFilled(false);
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 530, 120, 50));

        lbpastorname.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        getContentPane().add(lbpastorname, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 260, 40));

        btnMatrimonio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnMatrimonio.png"))); // NOI18N
        btnMatrimonio.setActionCommand("matrimonio");
        btnMatrimonio.setBorder(null);
        btnMatrimonio.setBorderPainted(false);
        btnMatrimonio.setContentAreaFilled(false);
        btnMatrimonio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMatrimonio.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnMatrimonio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(btnMatrimonio, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, 50));

        btnEconomica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnEconomica.png"))); // NOI18N
        btnEconomica.setActionCommand("economica");
        btnEconomica.setBorder(null);
        btnEconomica.setBorderPainted(false);
        btnEconomica.setContentAreaFilled(false);
        btnEconomica.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEconomica.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnEconomica.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(btnEconomica, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 180, -1));

        btnIglesia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnIglesia.png"))); // NOI18N
        btnIglesia.setActionCommand("iglesia");
        btnIglesia.setBorder(null);
        btnIglesia.setBorderPainted(false);
        btnIglesia.setContentAreaFilled(false);
        btnIglesia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnIglesia.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnIglesia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(btnIglesia, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 180, -1));

        btnOrganizacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnOrganizacion.png"))); // NOI18N
        btnOrganizacion.setActionCommand("organizacion");
        btnOrganizacion.setBorder(null);
        btnOrganizacion.setBorderPainted(false);
        btnOrganizacion.setContentAreaFilled(false);
        btnOrganizacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOrganizacion.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnOrganizacion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(btnOrganizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, 50));

        jlbFondoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoA.png"))); // NOI18N
        getContentPane().add(jlbFondoMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -6, 750, 610));

        getAccessibleContext().setAccessibleDescription("");

        setBounds(0, 0, 767, 637);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnEstudReaActionPerformed(java.awt.event.ActionEvent evt){
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDatLab;
    private javax.swing.JButton btnDatMinis;
    private javax.swing.JButton btnDocAnex;
    private javax.swing.JButton btnEconomica;
    private javax.swing.JButton btnEstudRea;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnIglesia;
    private javax.swing.JButton btnInfPersonal;
    private javax.swing.JButton btnMatrimonio;
    private javax.swing.JButton btnOrganizacion;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jlbFondoMenu;
    private javax.swing.JLabel lbpastorname;
    // End of variables declaration//GEN-END:variables

    @Override
    public void aggActionListener(ActionListener acL) {
      btnDatLab.addActionListener(acL);
      btnDatMinis.addActionListener(acL);
      btnDocAnex.addActionListener(acL);
      btnEstudRea.addActionListener(acL);
      btnGuardar.addActionListener(acL);
      btnInfPersonal.addActionListener(acL);
      btnSalir.addActionListener(acL);
      btnDocAnex.addActionListener(acL);
      btnIglesia.addActionListener(acL);
      btnOrganizacion.addActionListener(acL);
      btnMatrimonio.addActionListener(acL);
      btnEconomica.addActionListener(acL);
      
    }
    
    public JButton getBtnEconomica() {
        return btnEconomica;
    }

    public void setBtnEconomica(JButton btnEconomica) {
        this.btnEconomica = btnEconomica;
    }
    public JButton getBtnOrganizacion() {
        return btnOrganizacion;
    }

    public void setBtnOrganizacion(JButton btnOrganizacion) {
        this.btnOrganizacion = btnOrganizacion;
    }
    public JButton getBtnMatrimonio() {
        return btnMatrimonio;
    }

    public void setBtnMatrimonio(JButton btnMatrimonio) {
        this.btnMatrimonio = btnMatrimonio;
    }
    public JButton getBtnIglesia() {
        return btnIglesia;
    }

    public void setBtnIglesia(JButton btnIglesia) {
        this.btnIglesia = btnIglesia;
    }

    public JButton getBtnDatLab() {
        return btnDatLab;
    }

    public void setBtnDatLab(JButton btnDatLab) {
        this.btnDatLab = btnDatLab;
    }

    public JButton getBtnDatMinis() {
        return btnDatMinis;
    }

    public void setBtnDatMinis(JButton btnDatMinis) {
        this.btnDatMinis = btnDatMinis;
    }

    public JButton getBtnDocAnex() {
        return btnDocAnex;
    }

    public void setBtnDocAnex(JButton btnDocAnex) {
        this.btnDocAnex = btnDocAnex;
    }

    public JButton getBtnEstudRea() {
        return btnEstudRea;
    }

    public void setBtnEstudRea(JButton btnEstudRea) {
        this.btnEstudRea = btnEstudRea;
    }

    public JButton getBtnGuardar() {
        return btnGuardar;
    }

    public void setBtnGuardar(JButton btnGuardar) {
        this.btnGuardar = btnGuardar;
    }

    public JButton getBtnInfPersonal() {
        return btnInfPersonal;
    }

    public void setBtnInfPersonal(JButton btnInfPersonal) {
        this.btnInfPersonal = btnInfPersonal;
    }

    public JButton getBtnSalir() {
        return btnSalir;
    }

    public void setBtnSalir(JButton btnSalir) {
        this.btnSalir = btnSalir;
    }

    public JLabel getJlbFondoMenu() {
        return jlbFondoMenu;
    }

    public void setJlbFondoMenu(JLabel jlbFondoMenu) {
        this.jlbFondoMenu = jlbFondoMenu;
    }

    public JLabel getLbpastorname() {
        return lbpastorname;
    }

    public void setLbpastorname(JLabel lbpastorname) {
        this.lbpastorname = lbpastorname;
    }

    public JButton getBtnEconomica() {
        return btnEconomica;
    }

    public void setBtnEconomica(JButton btnEconomica) {
        this.btnEconomica = btnEconomica;
    }

    @Override
    public void aggKeyListener(KeyListener keyL) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void aggMouseListener(MouseListener mouseL) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
